apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-external-access
  namespace: kubeflow-user-example-com
spec:
  selector:
    matchLabels:
      app: frontend
  rules:
  - {}
