apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
  namespace: kubeflow-user-example-com 
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 2cassa2/kserve-frontend-ui:1.0.3
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
