apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kubeflow-user-example-com
  # namespace: frontend
spec:
  selector:
    app: frontend
  ports:
  # - port: 80
  - port: 8081
    targetPort: 5001
  type: LoadBalancer
  # type: ClusterIP
