apiVersion: v1
kind: Service
metadata:
  name: llm-ui
  namespace: kubeflow-user-example-com
spec:
  selector:
    app: llm-ui
  ports:
  # - port: 8081
  - port: 80
    targetPort: 8501
  type: LoadBalancer
  # type: ClusterIP
