apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-api
  namespace: kubeflow-user-example-com
  labels:
    app: llm-api
data:
  # model_name: "microsoft/Phi-3-mini-4k-instruct" # complete this with the model repo name
  model_name: "HuggingFaceH4/zephyr-7b-beta"